service: serverless-http-api
frameworkVersion: '3'

plugins:
    - serverless-offline
    - serverless-esbuild

provider:
    name: aws
    runtime: nodejs18.x

functions:
    productService:
        handler: src/services/product/ProductService.handler
        events:
            - httpApi:
                  path: /product/{productId}
                  method: get
                  response:
                      headers:
                          Content-Type: application/json
            - httpApi:
                  path: /product/{productId}
                  method: delete
                  response:
                      headers:
                          Content-Type: application/json
            - httpApi:
                  path: /product/{productId}
                  method: put
                  response:
                      headers:
                          Content-Type: application/json
            - httpApi:
                  path: /product
                  method: post
                  response:
                      headers:
                          Content-Type: application/json
