service: serverless-http-api
frameworkVersion: '3'

plugins:
    - serverless-offline
    - serverless-esbuild

provider:
    name: aws
    runtime: nodejs18.x

functions:
    productService:
        handler: src/services/product/ProductService.handler
        events:
            - httpApi:
                  path: /product
                  method: get
